language: node_js
node_js:
  - "6.1"
  - "5.11"
  - "4.4"
  - "0.12"
os:
  - linux
  - osx
before_script:
  - npm run build
script:
  - npm run review & npm test & npm link && npm run integration-tests
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
